### ISSUE TITLE
question: pas2js in Delphi 10.3.1 compile error and command line option

### ISSUE THREAD

**Issue by starwindz** [Kryuski/pas2js-for-delphi#1]
Thank you very much for your great work. I have two questions/

1. pas2js in Delphi 10.3.1 compile error (pasResolveEval.pas)
-  #0..#31,#127..#255,#$D800..#$ffff: 

2. i have changed above line to ' #0..#31,#127..#255:' and then exe created. but when pas2js run, some error occurred. what is proper usage of pas2js?
- can't find unit "System"

< Compile error message >
Checking project dependencies...
Compiling pas2js.dproj (Debug, Win32)
dcc32 command line for "pas2js.dpr"
  c:\program files (x86)\embarcadero\studio\20.0\bin\dcc32.exe -$O- -$W+ -$R+ -$Q+ --no-config -M -Q -TX.exe 
  -AGenerics.Collections=System.Generics.Collections;Generics.Defaults=System.Generics.Defaults;WinTypes=Winapi.Windows;WinProcs=Winapi.Windows;
  DbiTypes=BDE;DbiProcs=BDE;DbiErrs=BDE -DDEBUG;FPC_HAS_CPSTRING;WINDOWS;UsePChar;FPC -E..\..\..\bin -I..\..\packages;..\..\packages\pastojs\src;
  ..\..\packages\fcl-passrc\src;..\..\packages\fcl-js\src;..\..\packages\fcl-json\src;"c:\program files 
  (x86)\embarcadero\studio\20.0\lib\Win32\release";C:\Users\User\Documents\Embarcadero\Studio\20.0\Imports;"c:\program files 
  (x86)\embarcadero\studio\20.0\Imports";C:\Users\Public\Documents\Embarcadero\Studio\20.0\Dcp;"c:\program files (x86)\embarcadero\studio\20.0\include";
  D:\openfodder\dev\SynEdit-master\Source;D:\openfodder\dev\graphics32-master\Source -LEC:\Users\Public\Documents\Embarcadero\Studio\20.0\Bpl 
  -LNC:\Users\Public\Documents\Embarcadero\Studio\20.0\Dcp -NU..\..\..\Units\Win32-Debug -NSWinapi;System.Win;Data.Win;Datasnap.Win;Web.Win;Soap.Win;
  Xml.Win;Bde;System;Xml;Data;Datasnap;Web;Soap; -O..\..\packages;..\..\packages\pastojs\src;..\..\packages\fcl-passrc\src;..\..\packages\fcl-js\src;
  ..\..\packages\fcl-json\src;"c:\program files (x86)\embarcadero\studio\20.0\lib\Win32\release";
  C:\Users\User\Documents\Embarcadero\Studio\20.0\Imports;"c:\program files (x86)\embarcadero\studio\20.0\Imports";
  C:\Users\Public\Documents\Embarcadero\Studio\20.0\Dcp;"c:\program files (x86)\embarcadero\studio\20.0\include";
  D:\openfodder\dev\SynEdit-master\Source;D:\openfodder\dev\graphics32-master\Source -R..\..\packages;..\..\packages\pastojs\src;
  ..\..\packages\fcl-passrc\src;..\..\packages\fcl-js\src;..\..\packages\fcl-json\src;"c:\program files 
  (x86)\embarcadero\studio\20.0\lib\Win32\release";C:\Users\User\Documents\Embarcadero\Studio\20.0\Imports;"c:\program files 
  (x86)\embarcadero\studio\20.0\Imports";C:\Users\Public\Documents\Embarcadero\Studio\20.0\Dcp;"c:\program files (x86)\embarcadero\studio\20.0\include";
  D:\openfodder\dev\SynEdit-master\Source;D:\openfodder\dev\graphics32-master\Source -U..\..\packages;..\..\packages\pastojs\src;
  ..\..\packages\fcl-passrc\src;..\..\packages\fcl-js\src;..\..\packages\fcl-json\src;"c:\program files 
  (x86)\embarcadero\studio\20.0\lib\Win32\release";C:\Users\User\Documents\Embarcadero\Studio\20.0\Imports;"c:\program files 
  (x86)\embarcadero\studio\20.0\Imports";C:\Users\Public\Documents\Embarcadero\Studio\20.0\Dcp;"c:\program files (x86)\embarcadero\studio\20.0\include";
  D:\openfodder\dev\SynEdit-master\Source;D:\openfodder\dev\graphics32-master\Source -K00400000 
  -NBC:\Users\Public\Documents\Embarcadero\Studio\20.0\Dcp -NHC:\Users\Public\Documents\Embarcadero\Studio\20.0\hpp\Win32 -NO..\..\..\Units\Win32-Debug 
   pas2js.dpr   
[dcc32 Error] pasresolveeval.pas(821): E2030 Duplicate case label
[dcc32 Fatal Error] F2063 Could not compile used unit 'PasResolveEval.pas'
Failed
Elapsed time: 00:00:00.6

**Comment by Kryuski** [comment]
I updated the project, please try again with the updated version. I recomend to use Delphi 10.4 and above. Work in older versions of Delphi is not guaranteed.
